name: Homebrew Tap publisher
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish to Hombrew tap
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      RELEASE_TITLE: ${{github.event.release.name}}
      VERSION: ${{github.event.release.tag_name}}
      GITHUB_TOKEN: ${{ secrets.INTER_REPO_TOKEN }}
      #GITHUB_TOKEN: ${{ secrets.JOURNALSCRIPT_TOKEN }}
      GH_TOKEN: ${{ secrets.INTER_REPO_TOKEN }}
    steps:
      - name: Check out tap repository
        uses: actions/checkout@v3
        with:
          repository: al3jandr0/hombrew-tap
          token: ${{ secrets.INTER_REPO_TOKEN }}
      - name: Download latest release assets
        run: |
          gh release list --repo al3jandr0/journalscript
          gh release download --pattern '*.rb' --clobber --repo al3jandr0/journalscript
      - name: Commit formula
        run: |
          mkdir -p Formula
          cp -f journalscript.rb Formula/journalscript.rb
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Formula/journalscript.rb
          git commit -m "Update formula: ${RELEASE_TITLE}"
          git push origin main
      # Not creating a PR because of a bug in gh pr create
      # Refs:
      # - https://github.com/cli/cli/issues/575#issuecomment-1163143215
      # - https://github.com/cli/cli/issues/2691
      #- name: Create pr
      #  run: |
      #    gh pr create -d \
      #    --title "Update formula: ${RELEASE_TITLE}" \
      #    --body "Update formula: ${RELEASE_TITLE}" \
      #    --repo "al3jandr0/hombrew-tap" \
      #    --base "upstream/main" \
      #    --head "hombrew-tap:origin/journalscript-${VERSION}" \
      #    --label 'pr-pull'
