name: Homebrew Tap publisher
#run-name: Publishing release ${{ inputs.deploy_target }} by @${{ github.actor }}
on: release
#types: [published, released]

env:
  GITHUB_TOKEN: ${{ secrets.pat }}

jobs:
  publish:
    name: Publish to Hombrew tap
    runs-on: ubuntu-latest
    steps:
      - name: Check out tap repository
        uses: actions/checkout@v3
        with:
          repository: al3jandr0/hombrew-tap
      - name: Download latest release assets
        run: |
          gh release list --repo al3jandr0/journalscript
          gh release download --pattern '*.rb' --clobber --repo al3jandr0/journalscript
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
