name: Homebrew Tap publisher
on: release

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish to Hombrew tap
    runs-on: ubuntu-latest
    steps:
      - name: Check out tap repository
        uses: actions/checkout@v3
        with:
          repository: al3jandr0/hombrew-tap
      - name: Download latest release assets
        run: gh release download -D release/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit formula
        run: |
          mkdir -p Formula
          cp -f release/journalscript.rb Formula/journalscript.rb
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Formula/journalscript.rb
          git commit -m "Updates journalscript formula to version XYZ"
          git push -u origin journalscript-XYZ

  # create PR
