name: Hobrew Tap publisher
on:
  release:
# action types
# release
# prereleased
# published
# unpublished
# created
defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish to Hombrew tap
    runs-on: ubuntu-latest
    steps:
      - name: Check out tap repository
        uses: actions/checkout@v3
        with:
          repository: al3jandr0/hombrew-tap
          path: homebrew-tap
      - name: Download released formula
        run: |
          #echo "${{ github.event.release.assets }}"
          echo "${{ fromJson(github.event.release.assets) }}"
  # download release asset (formula)
  # replace downloaded formula in the repo
  # commit
  # push to new remote branch
  # create PR
