name: Homebrew Tap publisher
on:
  release:
    types: [published]
permissions:
  contents: write

jobs:
  publish:
    name: Publish to Hombrew tap
    runs-on: ubuntu-latest
    env:
      RELEASE_TITLE: ${{github.event.release.name}}
      VERSION: ${{github.event.release.tag_name}}
      GITHUB_TOKEN: ${{ secrets.JOURNALSCRIPT_TOKEN }}
    steps:
      - name: Check out tap repository
        uses: actions/checkout@v3
        with:
          repository: al3jandr0/hombrew-tap
          token: ${{ secrets.JOURNALSCRIPT_TOKEN }}
      - name: Download latest release assets
        run: |
          gh release list --repo al3jandr0/journalscript
          gh release download --pattern '*.rb' --clobber --repo al3jandr0/journalscript
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit formula
        run: |
          mkdir -p Formula
          cp -f journalscript.rb Formula/journalscript.rb
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Formula/journalscript.rb
          git commit -m "New release: ${RELEASE_TITLE}"
          git push -u origin main:journalscript-${VERSION}
