name: Homebrew Tap publisher
on: release

jobs:
  publish:
    name: Publish to Hombrew tap
    runs-on: ubuntu-latest
    steps:
      - name: Check out tap repository
        uses: actions/checkout@v3
        with:
          repository: al3jandr0/hombrew-tap
